site_name: pyquaero
site_author: Richard KÃ¶rber
site_url: https://shredzone.org/docs/pyquaero/index.html
theme:
    name: material
    font: false
    icon:
        logo: 'material/waves'
    palette:
        primary: 'blue'
        accent: 'deep orange'
extra_css:
  - css/firmware.css
markdown_extensions:
  - admonition
nav:
  - 'index.md'
  - 'firmware.md'
  - 'library.md'
  - 'tools.md'
  - 'raspberry.md'
  - Development: https://github.com/shred/pyquaero/
